version: "3.7"
services:
    flaskapp:
      build: 
        context : "."
        dockerfile : "Dockerfile"  
      image: flaskapp:latest
      ports:
        - "5000:5000"
      depends_on :
        - postgres
      environment:
        - POSTGRES_USER=user1
        - POSTGRES_PASSWORD=password1
        - POSTGRES_DB=db

    postgres :
      image : postgres:latest
      environment : 
        - POSTGRES_PASSWORD=password1
        - POSTGRES_USER=user1
        - POSTGRES_DB=db

      restart: "on-failure"